import { type Series } from '@/components/BookWidget'

export interface Book {
  slug: string
  title: string
  author: string
  authorDates?: string
  year: number
  yearDisplay: string
  era: 'ancient' | 'renaissance' | 'modern' | 'scientific-fiction'
  series: Series
  description?: string
  readingTime?: string
  pageCount?: number
}

export const books: Book[] = [
  // ============================================
  // ANCIENT (before 1500)
  // ============================================
  {
    slug: 'elements',
    title: 'Elements',
    author: 'Euclid',
    authorDates: 'fl. 300 BCE',
    year: -300,
    yearDisplay: '~300 BCE',
    era: 'ancient',
    series: 'geometry',
    description: 'The foundational text of geometry and mathematical proof. Thirteen books covering plane geometry, number theory, and solid geometry that shaped mathematics for two millennia.',
    readingTime: '20+ hours',
  },
  {
    slug: 'history-of-animals',
    title: 'The History of Animals',
    author: 'Aristotle',
    authorDates: '384–322 BCE',
    year: -350,
    yearDisplay: '~350 BCE',
    era: 'ancient',
    series: 'natural-philosophy',
    description: 'The first systematic study of zoology. Aristotle\'s careful observations of over 500 species laid the groundwork for biological classification.',
    readingTime: '15+ hours',
  },
  {
    slug: 'on-the-nature-of-things',
    title: 'On the Nature of Things',
    author: 'Lucretius',
    authorDates: '~99–55 BCE',
    year: -55,
    yearDisplay: '~55 BCE',
    era: 'ancient',
    series: 'natural-philosophy',
    description: 'Atomic theory in Latin verse. A poetic exposition of Epicurean philosophy arguing that everything is made of atoms moving through void.',
    readingTime: '8–10 hours',
  },
  {
    slug: 'almagest',
    title: 'Almagest',
    author: 'Ptolemy',
    authorDates: '~100–170 CE',
    year: 150,
    yearDisplay: '~150 CE',
    era: 'ancient',
    series: 'heavens',
    description: 'The astronomical encyclopedia that dominated Western and Islamic astronomy for over a thousand years. Geocentric, but mathematically sophisticated.',
    readingTime: '30+ hours',
  },
  {
    slug: 'hippocratic-corpus',
    title: 'Hippocratic Corpus',
    author: 'Hippocrates et al.',
    authorDates: '~460–370 BCE',
    year: -400,
    yearDisplay: '~400 BCE',
    era: 'ancient',
    series: 'medicine',
    description: 'The founding texts of Western medicine. Case studies, ethical principles, and the revolutionary idea that disease has natural, not supernatural, causes.',
    readingTime: '25+ hours',
  },
  {
    slug: 'on-the-sizes-and-distances',
    title: 'On the Sizes and Distances of the Sun and Moon',
    author: 'Aristarchus',
    authorDates: '~310–230 BCE',
    year: -250,
    yearDisplay: '~250 BCE',
    era: 'ancient',
    series: 'heavens',
    description: 'The first known attempt to calculate cosmic distances using geometry. Aristarchus also proposed a heliocentric model, seventeen centuries before Copernicus.',
    readingTime: '2–3 hours',
  },
  {
    slug: 'on-floating-bodies',
    title: 'On Floating Bodies',
    author: 'Archimedes',
    authorDates: '~287–212 BCE',
    year: -250,
    yearDisplay: '~250 BCE',
    era: 'ancient',
    series: 'forces-fields',
    description: 'The principles of hydrostatics and buoyancy. Contains the famous insight supposedly discovered in the bath: "Eureka!"',
    readingTime: '3–4 hours',
  },

  // ============================================
  // RENAISSANCE (1500–1800)
  // ============================================
  {
    slug: 'revolutions',
    title: 'On the Revolutions of Heavenly Spheres',
    author: 'Copernicus',
    authorDates: '1473–1543',
    year: 1543,
    yearDisplay: '1543',
    era: 'renaissance',
    series: 'heavens',
    description: 'The book that moved the Earth. Copernicus\'s mathematical argument for a sun-centered universe sparked the Scientific Revolution.',
    readingTime: '15+ hours',
  },
  {
    slug: 'de-humani-corporis',
    title: 'On the Fabric of the Human Body',
    author: 'Andreas Vesalius',
    authorDates: '1514–1564',
    year: 1543,
    yearDisplay: '1543',
    era: 'renaissance',
    series: 'medicine',
    description: 'A revolution in anatomy. Vesalius\'s detailed dissections and stunning illustrations overturned centuries of medical dogma.',
    readingTime: '20+ hours',
  },
  {
    slug: 'dialogue',
    title: 'Dialogue Concerning Two Chief World Systems',
    author: 'Galileo Galilei',
    authorDates: '1564–1642',
    year: 1632,
    yearDisplay: '1632',
    era: 'renaissance',
    series: 'heavens',
    description: 'Galileo\'s dramatic dialogue between defenders of Ptolemy and Copernicus. The book that led to his trial before the Inquisition.',
    readingTime: '12–15 hours',
  },
  {
    slug: 'micrographia',
    title: 'Micrographia',
    author: 'Robert Hooke',
    authorDates: '1635–1703',
    year: 1665,
    yearDisplay: '1665',
    era: 'renaissance',
    series: 'observers',
    description: 'The first scientific bestseller. Hooke\'s exquisite illustrations of the microscopic world — including the first description of cells — astonished readers.',
    readingTime: '8–10 hours',
  },
  {
    slug: 'principia',
    title: 'Principia Mathematica',
    author: 'Isaac Newton',
    authorDates: '1642–1727',
    year: 1687,
    yearDisplay: '1687',
    era: 'renaissance',
    series: 'forces-fields',
    description: 'The laws of motion and universal gravitation. Newton unified terrestrial and celestial mechanics in one of the most influential scientific works ever written.',
    readingTime: '40+ hours',
  },
  {
    slug: 'opticks',
    title: 'Opticks',
    author: 'Isaac Newton',
    authorDates: '1642–1727',
    year: 1704,
    yearDisplay: '1704',
    era: 'renaissance',
    series: 'forces-fields',
    description: 'Newton\'s exploration of light, colour, and prisms. More accessible than the Principia, it shaped our understanding of optics for centuries.',
    readingTime: '10–12 hours',
  },
  {
    slug: 'systema-naturae',
    title: 'Systema Naturae',
    author: 'Carl Linnaeus',
    authorDates: '1707–1778',
    year: 1735,
    yearDisplay: '1735',
    era: 'renaissance',
    series: 'living-world',
    description: 'The classification system for all living things. Linnaeus\'s binomial nomenclature (Homo sapiens, etc.) remains the foundation of biological taxonomy.',
    readingTime: '15+ hours',
  },
  {
    slug: 'experiments-on-air',
    title: 'Experiments and Observations on Different Kinds of Air',
    author: 'Joseph Priestley',
    authorDates: '1733–1804',
    year: 1774,
    yearDisplay: '1774',
    era: 'renaissance',
    series: 'chemistry',
    description: 'The discovery of oxygen (which Priestley called "dephlogisticated air"). A turning point in the history of chemistry.',
    readingTime: '6–8 hours',
  },
  {
    slug: 'chemical-history-candle',
    title: 'The Chemical History of a Candle',
    author: 'Michael Faraday',
    authorDates: '1791–1867',
    year: 1861,
    yearDisplay: '1861',
    era: 'renaissance',
    series: 'chemistry',
    description: 'Six beloved lectures on the science hidden in a candle flame. Faraday\'s gift for explanation made complex chemistry accessible to all.',
    readingTime: '4–5 hours',
  },

  // ============================================
  // MODERN (1800–1950)
  // ============================================
  {
    slug: 'origin-of-species',
    title: 'On the Origin of Species',
    author: 'Charles Darwin',
    authorDates: '1809–1882',
    year: 1859,
    yearDisplay: '1859',
    era: 'modern',
    series: 'living-world',
    description: 'The book that changed everything. Darwin\'s careful argument for evolution by natural selection revolutionised our understanding of life.',
    readingTime: '12–15 hours',
  },
  {
    slug: 'voyage-of-beagle',
    title: 'The Voyage of the Beagle',
    author: 'Charles Darwin',
    authorDates: '1809–1882',
    year: 1839,
    yearDisplay: '1839',
    era: 'modern',
    series: 'living-world',
    description: 'Darwin\'s account of his five-year voyage around the world. Part travel writing, part natural history, entirely delightful.',
    readingTime: '15–18 hours',
  },
  {
    slug: 'electromagnetic-field',
    title: 'A Dynamical Theory of the Electromagnetic Field',
    author: 'James Clerk Maxwell',
    authorDates: '1831–1879',
    year: 1865,
    yearDisplay: '1865',
    era: 'modern',
    series: 'forces-fields',
    description: 'The unification of electricity, magnetism, and light. Maxwell\'s equations are among the most elegant in all of physics.',
    readingTime: '8–10 hours',
  },
  {
    slug: 'plant-hybridization',
    title: 'Experiments on Plant Hybridization',
    author: 'Gregor Mendel',
    authorDates: '1822–1884',
    year: 1866,
    yearDisplay: '1866',
    era: 'modern',
    series: 'living-world',
    description: 'The foundation of genetics, ignored for 35 years. Mendel\'s meticulous pea experiments revealed the laws of heredity.',
    readingTime: '2–3 hours',
  },
  {
    slug: 'treatise-electricity-magnetism',
    title: 'A Treatise on Electricity and Magnetism',
    author: 'James Clerk Maxwell',
    authorDates: '1831–1879',
    year: 1873,
    yearDisplay: '1873',
    era: 'modern',
    series: 'forces-fields',
    description: 'Maxwell\'s comprehensive treatment of electromagnetism. Dense but foundational — Einstein kept a photograph of Maxwell on his wall.',
    readingTime: '50+ hours',
  },
  {
    slug: 'radioactive-substances',
    title: 'Researches on Radioactive Substances',
    author: 'Marie Curie',
    authorDates: '1867–1934',
    year: 1904,
    yearDisplay: '1904',
    era: 'modern',
    series: 'chemistry',
    description: 'Curie\'s doctoral thesis on radioactivity. The work that led to two Nobel Prizes and transformed our understanding of matter.',
    readingTime: '4–5 hours',
  },
  {
    slug: 'relativity',
    title: 'Relativity: The Special and General Theory',
    author: 'Albert Einstein',
    authorDates: '1879–1955',
    year: 1916,
    yearDisplay: '1916',
    era: 'modern',
    series: 'forces-fields',
    description: 'Einstein\'s own explanation of relativity for general readers. Space, time, and gravity made as accessible as possible by their discoverer.',
    readingTime: '5–6 hours',
  },
  {
    slug: 'what-is-life',
    title: 'What is Life?',
    author: 'Erwin Schrödinger',
    authorDates: '1887–1961',
    year: 1944,
    yearDisplay: '1944',
    era: 'modern',
    series: 'living-world',
    description: 'A physicist asks how life works. Schrödinger\'s speculations about the "hereditary code-script" inspired the discoverers of DNA.',
    readingTime: '4–5 hours',
  },
  {
    slug: 'cybernetics',
    title: 'Cybernetics',
    author: 'Norbert Wiener',
    authorDates: '1894–1964',
    year: 1948,
    yearDisplay: '1948',
    era: 'modern',
    series: 'mathematics',
    description: 'Control and communication in the animal and the machine. Wiener\'s founding text for the science of feedback and self-regulating systems.',
    readingTime: '10–12 hours',
  },

  // ============================================
  // SCIENTIFIC FICTION (Public Domain)
  // ============================================
  {
    slug: 'frankenstein',
    title: 'Frankenstein',
    author: 'Mary Shelley',
    authorDates: '1797–1851',
    year: 1818,
    yearDisplay: '1818',
    era: 'scientific-fiction',
    series: 'scientific-fiction',
    description: 'The first science fiction novel. A scientist creates life and confronts the consequences — a story that becomes more relevant every year.',
    readingTime: '6–8 hours',
  },
  {
    slug: 'twenty-thousand-leagues',
    title: 'Twenty Thousand Leagues Under the Sea',
    author: 'Jules Verne',
    authorDates: '1828–1905',
    year: 1870,
    yearDisplay: '1870',
    era: 'scientific-fiction',
    series: 'scientific-fiction',
    description: 'Captain Nemo\'s submarine voyage. Verne\'s detailed imagining of underwater exploration anticipated submarines by decades.',
    readingTime: '10–12 hours',
  },
  {
    slug: 'time-machine',
    title: 'The Time Machine',
    author: 'H.G. Wells',
    authorDates: '1866–1946',
    year: 1895,
    yearDisplay: '1895',
    era: 'scientific-fiction',
    series: 'scientific-fiction',
    description: 'The invention of time travel fiction. Wells\'s journey to the far future is also a meditation on evolution, entropy, and class.',
    readingTime: '3–4 hours',
  },
  {
    slug: 'war-of-worlds',
    title: 'The War of the Worlds',
    author: 'H.G. Wells',
    authorDates: '1866–1946',
    year: 1898,
    yearDisplay: '1898',
    era: 'scientific-fiction',
    series: 'scientific-fiction',
    description: 'The Martian invasion that created a genre. Wells turned the British Empire\'s colonial violence back on itself.',
    readingTime: '5–6 hours',
  },
  {
    slug: 'flatland',
    title: 'Flatland',
    author: 'Edwin Abbott',
    authorDates: '1838–1926',
    year: 1884,
    yearDisplay: '1884',
    era: 'scientific-fiction',
    series: 'geometry',
    description: 'A romance of many dimensions. Abbott\'s satire uses two-dimensional beings to explore geometry, perception, and Victorian society.',
    readingTime: '2–3 hours',
  },
  {
    slug: 'island-of-doctor-moreau',
    title: 'The Island of Doctor Moreau',
    author: 'H.G. Wells',
    authorDates: '1866–1946',
    year: 1896,
    yearDisplay: '1896',
    era: 'scientific-fiction',
    series: 'scientific-fiction',
    description: 'Vivisection and the boundaries of humanity. Wells\'s most disturbing novel asks what makes us human.',
    readingTime: '4–5 hours',
  },
  {
    slug: 'rur',
    title: 'R.U.R.',
    author: 'Karel Čapek',
    authorDates: '1890–1938',
    year: 1920,
    yearDisplay: '1920',
    era: 'scientific-fiction',
    series: 'scientific-fiction',
    description: 'The play that invented the word "robot". Čapek\'s artificial workers raise questions about labour, humanity, and creation.',
    readingTime: '2–3 hours',
  },
]

// Helper functions
export function getBooksByEra(era: Book['era']): Book[] {
  return books.filter(book => book.era === era).sort((a, b) => a.year - b.year)
}

export function getBookBySlug(slug: string): Book | undefined {
  return books.find(book => book.slug === slug)
}